const url = process.env.PUBLIC_URL;
const Data = [
    {
        id: 1,
        names: `Virtual Home Staging`,
        thumbnaile: url+`/vendor/images/partner.jpg`,
        symbol: `₹`,
        price: `2000`,
        minTime: `12 hr`,
        maxTime: `24hr`,
        rivision: `3`,
        slug: `virtual-home-staging_2000_3_rupee`,
    },
    {
        id: 2,
        names: `Virtual Interior Staging`,
        thumbnaile: url+`/vendor/images/partner.jpg`,
        symbol: `₹`,
        price: `2000`,
        minTime: `12 hr`,
        maxTime: `24hr`,
        rivision: `3`,
        slug: `virtual-interior-staging_2000_3_rupee`,
    },
    {
        id: 3,
        names: `Virtual Home Decor`,
        thumbnaile: url+`/vendor/images/partner.jpg`,
        symbol: `₹`,
        price: `2000`,
        minTime: `12 hr`,
        maxTime: `24hr`,
        rivision: `3`,
        slug: `virtual-home-decor_2000_3_rupee`,
    },
    {
        id: 11,
        names: `Interior Home Staging`,
        thumbnaile: url+`/vendor/images/partner.jpg`,
        symbol: `₹`,
        price: `2000`,
        minTime: `12 hr`,
        maxTime: `24hr`,
        rivision: `3`,
        slug: `Interior-home-staging_2000_3_rupee`,
    },
    {
        id: 21,
        names: `Virtual Interior decor`,
        thumbnaile: url+`/vendor/images/partner.jpg`,
        symbol: `₹`,
        price: `2000`,
        minTime: `12 hr`,
        maxTime: `24hr`,
        rivision: `3`,
        slug: `virtual-interior-decor_2000_3_rupee`,
    },
    {
        id: 32,
        names: `Virtual Home interior`,
        thumbnaile: url+`/vendor/images/partner.jpg`,
        symbol: `₹`,
        price: `2000`,
        minTime: `12 hr`,
        maxTime: `24hr`,
        rivision: `3`,
        slug: `virtual-home-interior_2000_3_rupee`,
    },
];
const Custom = [
    {
        id: 1,
        names: `Virtual Home Staging Custom `,
        thumbnaile: url+`/vendor/images/partner.jpg`,
        symbol: `₹`,
        price: `2000`,
        minTime: `12 hr`,
        maxTime: `24hr`,
        rivision: `3`,
        slug: `virtual-home-staging_2000_3_rupee`,
    },
    {
        id: 42,
        names: ` Custom Virtual Interior Staging`,
        thumbnaile: url+`/vendor/images/partner.jpg`,
        symbol: `₹`,
        price: `2000`,
        minTime: `12 hr`,
        maxTime: `24hr`,
        rivision: `3`,
        slug: `virtual-interior-staging_2000_3_rupee`,
    },
    {
        id: 35,
        names: `Virtual Custom  Home Decor`,
        thumbnaile: url+`/vendor/images/partner.jpg`,
        symbol: `₹`,
        price: `2000`,
        minTime: `12 hr`,
        maxTime: `24hr`,
        rivision: `3`,
        slug: `virtual-home-decor_2000_3_rupee`,
    },
];
export default Data;
export { Custom }